---
- name: Update apt cache
  apt:
    update_cache: true
  changed_when: false

- name: Download ASC file
  apt_key:
    url: "{{ vscode_microsoft_asc_url }}"
    state: present

- name: Add vscode repo into sources list
  apt_repository:
    repo: "{{ vscode_apt_repo }}"
    state: present

- name: Install vscode
  apt:
    name: "code"
    state: present
