---
- name: Update apt cache
  become: yes
  apt:
    update_cache: yes
  changed_when: false

- name: Download ASC file
  apt_key: 
    url: "{{ vscode_microsoft_asc_url }}"
    state: present

- name: Add vscode repo into sources list
  apt_repository:
    repo: "{{ vscode_apt_repo }}"
    state: present

- name: Install vscode
  become: yes
  apt:
    name: "code"
    state: present